### ISSUE TITLE
BUILD FAILURE ON CENTOS7

### ISSUE THREAD

**Issue by chitenderkumar** [AuspeXeu/openvpn-status#11]
below is my cfg.json
{
  "port": 3013,
  "bind": "10.0.0.180",
  "servers": [{"id": 0,"name": "Server"}],
  "ipFile": "./GeoLite2-City.mmdb"
}

when i executed `npm run build` it got failed with below error logs:
`> openvpn-status@4.0.17 build /home/centos/openvpn-status/openvpn-status
> node build/build.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/centos/openvpn-status/openvpn-status/build/check-versions.js:2:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Linux 3.10.0-327.10.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "run" "build"
npm ERR! node v6.12.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! openvpn-status@4.0.17 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openvpn-status@4.0.17 build script 'node build/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the openvpn-status package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs openvpn-status
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls openvpn-status
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /home/centos/openvpn-status/openvpn-status/npm-debug.log`

i am attaching the  /home/centos/openvpn-status/openvpn-status/npm-debug.log
[logs.txt](https://github.com/AuspeXeu/openvpn-status/files/1841064/logs.txt)

kindly let us know to fix this.

**Comment by AuspeXeu** [comment]
Can you paste your `package.json` ? Did you run `npm install` beforehand?

**Comment by chitenderkumar** [comment]
ok, i didnt executed the `npm install`.

post executing the `npm install` it worked. but when i am accessing the web interface it is blank.
![screen shot 2018-03-23 at 4 10 48 pm](https://user-images.githubusercontent.com/35098683/37825132-d04ba7c4-2eb4-11e8-9d0c-dcf25d26e76d.png)

can you please comment on this.

**Comment by AuspeXeu** [comment]
Well, did you set up the status.sh correctly?

**Comment by chitenderkumar** [comment]
yes, below are the content of `status.sh`

`#!/bin/bash
HOST="10.0.0.180"
PORT="3013"
SERVER="0"

JSON="{\"script\":\"$script_type\",\"pub\":\"$trusted_ip\",\"cn\":\"$common_name\",\"vpn\":\"$ifconfig_pool_remote_ip\"}"
curl -H "Content-Type: application/json" -X POST -d "$JSON" "http://$HOST:$PORT/server/$SERVER/script" --connect-timeout 2 -m 3
exit 0`

and i made the entry in server.conf as below:
`
client-connect /etc/openvpn/status.sh
client-disconnect /etc/openvpn/status.sh
`

**Comment by AuspeXeu** [comment]
did you put `script-security 2` into your server configuration?

**Comment by chitenderkumar** [comment]
yes it is there

**Comment by AuspeXeu** [comment]
Are you using `pm2` ? If so, can you maybe send the log `pm2 logs`?

**Comment by chitenderkumar** [comment]
i am not sure it. can you let me know how can i check whether pm2 is in use or not and where to find logs?

**Comment by AuspeXeu** [comment]
How do you start the server?

**Comment by chitenderkumar** [comment]
with below commands:
pm2 start pm2.json
pm2 save

**Comment by AuspeXeu** [comment]
yeah so you can simply type `pm2 logs` to see the logfile.

**Comment by chitenderkumar** [comment]
[root@ip-10-0-0-180 log]# pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | [2018-03-23 10:11:13] PM2 log: Time                 : Fri Mar 23 2018 10:11:13 GMT+0000 (UTC)
PM2        | [2018-03-23 10:11:13] PM2 log: PM2 version          : 2.10.1
PM2        | [2018-03-23 10:11:13] PM2 log: Node.js version      : 6.12.3
PM2        | [2018-03-23 10:11:13] PM2 log: Current arch         : x64
PM2        | [2018-03-23 10:11:13] PM2 log: PM2 home             : /root/.pm2
PM2        | [2018-03-23 10:11:13] PM2 log: PM2 PID file         : /root/.pm2/pm2.pid
PM2        | [2018-03-23 10:11:13] PM2 log: RPC socket file      : /root/.pm2/rpc.sock
PM2        | [2018-03-23 10:11:13] PM2 log: BUS socket file      : /root/.pm2/pub.sock
PM2        | [2018-03-23 10:11:13] PM2 log: Application log path : /root/.pm2/logs
PM2        | [2018-03-23 10:11:13] PM2 log: Process dump file    : /root/.pm2/dump.pm2
PM2        | [2018-03-23 10:11:13] PM2 log: Concurrent actions   : 2
PM2        | [2018-03-23 10:11:13] PM2 log: SIGTERM timeout      : 1600
PM2        | [2018-03-23 10:11:13] PM2 log: ===============================================================================
PM2        | [2018-03-23 10:11:13] PM2 log: Starting execution sequence in -fork mode- for app name:openvpn-status id:0
PM2        | [2018-03-23 10:11:13] PM2 log: App name:openvpn-status id:0 online

/root/.pm2/logs/openvpn-status-out-0.log last 15 lines:
/root/.pm2/logs/openvpn-status-error-0.log last 15 lines:

log files are blank.

**Comment by AuspeXeu** [comment]
Yeah, that is looking good. Have you reconnected one of your VPN clients while the server is running?

**Comment by chitenderkumar** [comment]
yes, it is still blank.

**Comment by AuspeXeu** [comment]
Hmmm ... hard to debug from here in that case. Maybe you can execute the `status.sh` from the command line and see what the output is?

**Comment by chitenderkumar** [comment]
below is the content of status.sh
`#!/bin/bash
HOST="10.0.0.180"
PORT="3013"
SERVER="0"

JSON="{\"script\":\"$script_type\",\"pub\":\"$trusted_ip\",\"cn\":\"$common_name\",\"vpn\":\"$ifconfig_pool_remote_ip\"}"
curl -H "Content-Type: application/json" -X POST -d "$JSON" "http://$HOST:$PORT/server/$SERVER/script" --connect-timeout 2 -m 3
exit 0`

and i got BAD Request when i executed the status.sh

**Comment by AuspeXeu** [comment]
Which status code is that?

**Comment by chitenderkumar** [comment]
[root@ip-10-0-0-180 openvpn]# curl -H "Content-i -Type: application/json" -X POST -d "$JSON" "http://10.0.0.180:3013/server/0/script"
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>TypeError: Cannot read property &#39;trim&#39; of undefined<br> &nbsp; &nbsp;at app.post (/home/centos/openvpn-status/openvpn-status/server.js:103:33)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/centos/openvpn-status/openvpn-status/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/home/centos/openvpn-status/openvpn-status/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at validateServer (/home/centos/openvpn-status/openvpn-status/server.js:96:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/centos/openvpn-status/openvpn-status/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/home/centos/openvpn-status/openvpn-status/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at Route.dispatch (/home/centos/openvpn-status/openvpn-status/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/centos/openvpn-status/openvpn-status/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /home/centos/openvpn-status/openvpn-status/node_modules/express/lib/router/index.js:281:22<br> &nbsp; &nbsp;at param (/home/centos/openvpn-status/openvpn-status/node_modules/express/lib/router/index.js:354:14)<br> &nbsp; &nbsp;at param (/home/centos/openvpn-status/openvpn-status/node_modules/express/lib/router/index.js:365:14)<br> &nbsp; &nbsp;at Function.process_params (/home/centos/openvpn-status/openvpn-status/node_modules/express/lib/router/index.js:410:3)<br> &nbsp; &nbsp;at next (/home/centos/openvpn-status/openvpn-status/node_modules/express/lib/router/index.js:275:10)<br> &nbsp; &nbsp;at jsonParser (/home/centos/openvpn-status/openvpn-status/node_modules/body-parser/lib/types/json.js:118:7)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/centos/openvpn-status/openvpn-status/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (/home/centos/openvpn-status/openvpn-status/node_modules/express/lib/router/index.js:317:13)<br> &nbsp; &nbsp;at /home/centos/openvpn-status/openvpn-status/node_modules/express/lib/router/index.js:284:7<br> &nbsp; &nbsp;at Function.process_params (/home/centos/openvpn-status/openvpn-status/node_modules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/home/centos/openvpn-status/openvpn-status/node_modules/express/lib/router/index.js:275:10)<br> &nbsp; &nbsp;at expressInit (/home/centos/openvpn-status/openvpn-status/node_modules/express/lib/middleware/init.js:40:5)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/centos/openvpn-status/openvpn-status/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (/home/centos/openvpn-status/openvpn-status/node_modules/express/lib/router/index.js:317:13)</pre>
</body>
</html>

**Comment by AuspeXeu** [comment]
Yeah, that's because $JSON carries no content :) Try the following before you curl `JSON="{"script":"client-connect","pub":"0.0.0.0","cn":"tester","vpn":"10.0.0.0"}"`

**Comment by chitenderkumar** [comment]
ok, thanks.

now i am able to see the status. now would it be possible that i can see how many users are rite now logged into my OpenVPN server?

**Comment by AuspeXeu** [comment]
So this means the test works? I wonder now because you should be able to see _all_ clients maybe restart your openvpn server.

**Comment by chitenderkumar** [comment]
so what should be the JSON content in status.sh? if i use static values in it, then every time a new client get connected it displays only as `tester` and also post if client has disconnected it stays in list.

so can we tweak it so that i can get the list of users those are connected to my OpenVPN server any given time. like in list i would get `username`, there `public-ip` from where they are connected to the openVpn server and the time since they are connected.

**Comment by AuspeXeu** [comment]
I have no idea what your current setup is. The JSON thing I posted earlier was just to test *not* to modify the `status.sh`.

**Comment by chitenderkumar** [comment]
so let me explain you my setup. 
* i am running openVpn server 2.4.4-1.el7.x86_64

my requirement is to monitor how many users are connected to my openvpn server and what bandwidth they are consuming.

i restored the `status.sh` as it should be. post that i restarted my openVpn server. but i am getting `Bad Request` in logs because the variables which are used in JSON they are not able to succesfully bieng parsed from openVpn server to the JSON element. below is the JSON schema which is in `status.sh`
`JSON="{\"script\":\"$script_type\",\"pub\":\"$trusted_ip\",\"cn\":\"$common_name\",\"vpn\":\"$ifconfig_pool_remote_ip\"}"`

is there anyway by which i can check what are the values parsed by openVpn server for above variables.

**Comment by AuspeXeu** [comment]
Can you send the non-sensitive parts of your `server.conf`? i.e. leave the keys and the url/ip out.

**Comment by chitenderkumar** [comment]
thanks for support mate. i was able to fix this. to debug the issue i explicitely added the echo statement in `status.sh` where i found that variable common_name was blank due this JSON schema was not valid. post that i checked the env variables which were creating while client get connect. so the required variable is `username`. i changed the variable to `$username` from `$common_name`. then it worked as expected.

Now i have suggestion regarding modifying the UI and adding the aditional functions in it. would you be interested on this.

**Comment by AuspeXeu** [comment]
Oh, this might be the case if you use password/username authentication? Is this the case for you?

Always happy to hear suggestions :)

**Comment by chitenderkumar** [comment]
Thanks.

rite now we get two information from the UI. one how many users are connected to my openVPN server and from what PublicIP. and second one is we get the event details. in event details we only get the user connect, dis-connect and re-connect.

in addition to above functionality it would be great if we can add below functionality:
* to provide status of bandwidth usage as per user.
* to provide status since when is user connected to the VPN server.
* to add alert mechanism: let say we defined a list of Ips and webSite which only can be access by the VPNserver clients. if they visit any Ips or WebSite apart from the provisioned we should get alert over the UI.
* to alert when user use heavy bandwidth.

let me know your comments on this.

**Comment by AuspeXeu** [comment]
Well, the time since when the client is connected is the last column in the clients table. As for bandwidth I don't know how we would access that information. Are you talking current bandwidth consumption or overall data transferred? Regarding your idea about websites, I am afraid that's generally not possible as the traffic is encrypted and I would argue that there are quite some privacy concerns with decrypting it intermediately. What are the reasons for these requirements?

**Comment by chitenderkumar** [comment]
so mainly we provide VPN connections to allow users to securely access the critical infrastructure. and any user can misuse it to access some malicious or any web traffic which can compromise the compliance standard. to avoid this many organisations implement the firewalls. which incur the additional infra cost and manpower. if its possible to apply such mechanism in the current mechanism then it wont require to implement additional firewall. user can simply put list of hostname or ips which needed to block.

**Comment by AuspeXeu** [comment]
I understand now. However, it seems to me that a firewall is still a better solution for exactly this. I'd be happy to integrate some sort of bandwidth usage statistics though?!
