### ISSUE TITLE
Windows Installation

### ISSUE THREAD

**Issue by xinthose** [AuspeXeu/openvpn-status#13]
Hello.  I have successfully completed all of your installation steps, but this URL: http://127.0.0.1:3013/ does not connect to anything.  Do I need to host the node application using ISS or something?

**Comment by AuspeXeu** [comment]
You installed it on the local machine? (You don't need ISS)

**Comment by xinthose** [comment]
Yes, on the machine running the OpenVPN server.  I used node.js 8.11.1.  Isn't there a node command I need to run?  Like `ng serve`.

**Comment by AuspeXeu** [comment]
Try `node server.js`

**Comment by xinthose** [comment]
OK.  I will try that tomorrow at work.  Thank you for your help.

**Comment by xinthose** [comment]
Hello.  I get an error with that command: 
```
C:\Program Files (x86)\EleMech\openvpn-status-4.0.18\node_modules\nconf\lib\ncon
f\stores\file.js:170
    throw new Error("Error parsing your configuration file: [" + this.file + ']:
 ' + ex.message);
    ^

Error: Error parsing your configuration file: [cfg.json]: Unexpected token { in
JSON at position 1
    at exports.File.File.loadSync (C:\Program Files (x86)\EleMech\openvpn-status
-4.0.18\node_modules\nconf\lib\nconf\stores\file.js:170:11)
    at exports.Provider.Provider.add (C:\Program Files (x86)\EleMech\openvpn-sta
tus-4.0.18\node_modules\nconf\lib\nconf\provider.js:136:23)
    at exports.Provider.Provider.file (C:\Program Files (x86)\EleMech\openvpn-st
atus-4.0.18\node_modules\nconf\lib\nconf\provider.js:63:15)
    at Object.<anonymous> (C:\Program Files (x86)\EleMech\openvpn-status-4.0.18\
server.js:17:6)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by xinthose** [comment]
That works, once I have the `cfg.json` setup correctly without extra commas, etc.  I can see the page in Chrome but with no data.  The styling seems to be off as well:
![capture](https://user-images.githubusercontent.com/12835202/38618599-bff4d918-3d5f-11e8-9215-f9f5168d0962.PNG)

**Comment by AuspeXeu** [comment]
Which setup steps have you performed? Do you have internet on that machine? It seems like the icons are not loaded. Further, have you set up the `status.sh` as described?

**Comment by xinthose** [comment]
I have performed all setups.  I do have internet on that machine.  I have setup `status.sh` as described, although in Windows I went to file properties >> Security >> Users >> Full Control.  The file is in C:\Program Files\OpenVPN\config, next to m2mserver.ovpn

Is your application able to work on Windows?  Will the bash script execute properly?  Maybe I should try this in Linux instead.

**Comment by AuspeXeu** [comment]
That is a good question. I never tried it on a windows machine. It is very possible that you'll have to write an equivalent shell script.

**Comment by Orfeous** [comment]
status.sh will not do anything on windows. It's for linux shell only.
Probably a .bat or .cmd file could do the job.
But pelase note that the syntax is different on windows.

**Comment by AuspeXeu** [comment]
@xinthose I added `status.bat` for this. Maybe you could give it a go :)

**Comment by xinthose** [comment]
Thank you for that.  These lines show in the server log when the client unsuccessfully tries to connect: 
`WARNING: Failed running command (--client-connect): returned error code 1`
`SENT CONTROL [elemech_service_2]: 'AUTH_FAILED' (status=1)`

**Comment by AuspeXeu** [comment]
So you can now see the connected clients? :) Regarding the icons, I would check the console of your browser. Maybe you can send a screenshot of the errors you see?

**Comment by xinthose** [comment]
OK.  I will try `0.0.0.0`.  Thank you.  
Correct.  I can now see the connected clients.  I will look at the console output tomorrow.

**Comment by xinthose** [comment]
Changing the binding to `0.0.0.0` worked for me.  These are the errors I am getting in the console:
![capture](https://user-images.githubusercontent.com/12835202/42453527-9f90a84e-8352-11e8-940e-dc02c4469517.PNG)

**Comment by AuspeXeu** [comment]
Can you download the latest `index.html` from this repository and run `npm run build` and check again?

**Comment by xinthose** [comment]
That worked!  Thank you again.  

My last Windows question is this: will the server automatically run after a reboot?  If not then how can I do this?
