### ISSUE TITLE
Not opening the HTTP port

### ISSUE THREAD

**Issue by BenRLewis** [AuspeXeu/openvpn-status#157]
Hi,
Trying to get this working with an existing OpenVPN setup, I'm getting no console output beynd the following 
```
openvpn-status    |
openvpn-status    | > openvpn-status@4.2.3 start /usr/src/app
openvpn-status    | > node server.js
openvpn-status    |
openvpn-status    | (node:18) [SEQUELIZE0004] DeprecationWarning: A boolean value was passed to options.operatorsAliases. This is a no-op with v5 and should be removed
```

The HTTP port on the host is never being opened, the config seems to be right, as before that, it was grumbling that it couldn't reach the management port.

I've tried using the Docker image with exactly the same results.

I'm trying to connect to the latest version of the kylemanna/openvpn server. 

Any input greatly appreciated.

**Comment by AuspeXeu** [comment]
Did you specify the correct `bind` option?

**Comment by BenRLewis** [comment]
That solved it, thanks
