### ISSUE TITLE
Wrong path?

### ISSUE THREAD

**Issue by thijsvdc** [AuspeXeu/openvpn-status#16]
Hi,

I followed the Installation guide, but tried to install openvpn-status on a standalone machine. The OpenVPN server is running on another system in the same LAN.

OS: Ubuntu 16.04.4 LTS
Node version: v10.5.0

When I navigate to http://<ip>:3013, I get this error (which is also shown in the logs):
Error: ENOENT: no such file or directory, stat '/home/<username>/openvpn-status/dist/index.html'

Indeed, there is no "dist" folder in openvpn-status.

Any idea?

Thanks!

**Comment by AuspeXeu** [comment]
It seems like you didn't ru `npm run build` ?

**Comment by thijsvdc** [comment]
Well, it seems that you're right :)
