### ISSUE TITLE
docker configuration handling

### ISSUE THREAD

**Issue by datablitz7** [AuspeXeu/openvpn-status#160]
I am trying to run this on docker , however it is unclear what is the expected/recommended way to pass the "bind" option to the app. Inside the container, I can see the cfg.json but this is not editable in any docker compatible/acceptable way. The cfg,json file contains some default values and there is neither logging nor output to show what parameters the app is running on. Your insight would be most appreciated.

**Comment by AuspeXeu** [comment]
This is actually a good point. A volume might be a good way to make the configuration editable from the host machine. However, how would you connect to the management port from within the openvpn-status docker container?

**Comment by datablitz7** [comment]
I tried a volume for cfg.json and it worked. My OpenVPN server is running on the host and I just configured the management port to listen on the docker bridge IP. Worked like a charm (data was a little weird, but this is for a new issue). Here is my docker-compose stanza for it:

```yml
openvpn-status:
    image: auspexeu/openvpn-status
    container_name: openvpn-status
    restart: "unless-stopped"
    ports:
        - '${LAN_IP}:3013:3013'
    environment:
        - AUTH_USERNAME="${VPN_AUTH_NAME}"
        - AUTH_PASSWORD="${VPN_PASSWORD}"
        - VPN_NAME="${VPN_NAME}"
        - VPN_HOST="${DOCKER_BRIDGE_IP}"
        - VPN_MAN_PORT="${VPN_MAN_PORT}"
        - VPN_DATE_FORMAT="DD/MM/YYYY HH:mm"
   volumes:
        - './openvpn-status/cfg.json:/usr/src/app/cfg.json'

**Comment by AuspeXeu** [comment]
If you mount the `cfg.json` as volume, you can omit all the `environment:` variables and configure all of that directly in the `cfg.json`.

Regarding the docker bridge IP, is that one static?

**Comment by datablitz7** [comment]
Yes, of course you can do everything on the cfg, I just wanted to point out that mixing and matching can also work. A docker bridge has a static IP on the host in a unique (hopefully) subnet, and containers assigned to it are then getting IP addresses from the subnet. This allows inter-container and container-host communication without having to use any "real" networks you might be routing out of your host.

**Comment by AuspeXeu** [comment]
That's cool. I didn't know this was possible so I had the openvpn-status running outside a container on the bare machine, just like the openvpn server. Thanks for the pointer!

**Comment by datablitz7** [comment]
No problem. I think it was a nice addition.
