### ISSUE TITLE
Can't connect openvpn management console

### ISSUE THREAD

**Issue by 1Stedy** [AuspeXeu/openvpn-status#171]
When app is running I can't connect openvpn management console. So any additional monitoring with telnet cannot be used (I use it for zabbix). Is there any workaround?

**Comment by AuspeXeu** [comment]
Why can you not connect?

**Comment by 1Stedy** [comment]
I made a mistake in description of the issue. I can connect, but can't get any answer from the management console.

So I can do this:
```
[user@server ~]$ telnet localhost 7500
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
load-stats
```
and nothing happens, session not responding to any command
If your app is not running I get this:
```
[user@server ~]$ telnet localhost 7500
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
>INFO:OpenVPN Management Interface Version 1 -- type 'help' for more info
load-stats
SUCCESS: nclients=0,bytesin=0,bytesout=0
```
App is working as systemd service
```
[Unit]
Description=OpenVPN Status
After=network.target

[Service]
User=root
WorkingDirectory=/etc/openvpn-status
ExecStart=/usr/bin/node server.js
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
```

**Comment by AuspeXeu** [comment]
How does your openvpn configuration file look like?

**Comment by 1Stedy** [comment]
```
port 1194

proto udp
dev tun
ca ca.crt
cert vpn-server.crt
key vpn-server.key
dh dh.pem
key-direction 0

server x.x.x.x 255.255.255.0
#ifconfig-pool-persist ipp.txt
push "route x.x.x.x 255.255.0.0"
push "route x.x.x.x 255.255.0.0"
push "dhcp-option DNS x.x.x.x"
push "dhcp-option DNS x.x.x.x"
push "block-outside-dns"
topology subnet
keepalive 10 120
tls-crypt vpn.tlsauth
cipher AES-256-CBC
user nobody
group nobody
persist-key
persist-tun
verify-client-cert none
duplicate-cn

username-as-common-name
auth SHA256
plugin /usr/lib64/openvpn/plugins/openvpn-plugin-auth-pam.so vpn

status  /var/log/openvpn-status.log
log     /var/log/openvpn.log
verb 2
explicit-exit-notify 1

management 127.0.0.1 7500
```

**Comment by AuspeXeu** [comment]
That's strange... since this is an openvpn issue I cannot really help you I am afraid. If I were you, I would check the openvpn log for error messages.

**Comment by 1Stedy** [comment]
I tried to open two telnet connections at one time and second just freezes. I know how to solve this, your app should close connection after answer received (as command _echo status | nc localhost 7500_ does). If you make it with configurable timeout between requests (every 5 sec, for example) it will be great.

Openvpn just say something like "pipe error" in logs, I think it just can't handle two sessions.

P.S. Openvpn log should not be spammed with management console connection/disconnection log if use verbose level 2.

**Comment by AuspeXeu** [comment]
Why would you need to have two connections?

**Comment by 1Stedy** [comment]
Because I monitor statistics by zabbix. Script parses output of **echo "load-stats" | nc localhost 7500** to get actual clients number and traffic. Maybe I will add statistics by user. And I also want to get your app working because it is cool for manual management and I like geolocation feature

**Comment by AuspeXeu** [comment]
I see. So what you would need for this to work is that no permanent telnet connection is required. However, this prevents my app to provide realtime data/events which I think is quite a cool feature by itself. The ideal solution in my opinion would be to have openvpn-status to provide a bidirectional telnet interface itself which is passed through to the openvpn telnet.

**Comment by 1Stedy** [comment]
Yeah, it's a good idea. Will you add this feature later?

**Comment by AuspeXeu** [comment]
I have not planned this hah. You're more than welcome to contribute to this :)

**Comment by 1Stedy** [comment]
I don't know js))
