### ISSUE TITLE
Multiple servers not on same LAN

### ISSUE THREAD

**Issue by jonesthesubmarine** [AuspeXeu/openvpn-status#172]
Hi, trying to get this to monitor multiple servers across the internet. When I run this on the same LAN it works great. Would ssh forwarding be an option? Maybe using autossh to keep the tunnel alive? Example from the openvpn server; sudo ssh -4v -N -R 5001:127.0.0.1:5555 monitor@123.456.789.012 and on the monitoring server I have in the cfg.json; "servers": [{"name": "Server","host": "127.0.0.1","man_port": 5001}],

Would like to just specify the servers in the cfg.json file but the openvpn management data is unencrypted and we don't want that going over the internet.

**Comment by AuspeXeu** [comment]
ssh port forwarding would imo be the best option :)

**Comment by jonesthesubmarine** [comment]
I guess you're right. Wish the management interface could do TLS. Would solve many issues.

**Comment by AuspeXeu** [comment]
Yeah ... it's a weird choice to do telnet for this. I guess it's probably an artifact from the early stages of the project.

**Comment by AuspeXeu** [comment]
Stale.
