### ISSUE TITLE
Date and Time format

### ISSUE THREAD

**Issue by xinthose** [AuspeXeu/openvpn-status#18]
Hello,

The application is running great on Windows.  I live in America and would like to see the date in this format: day/month/year then the time (7/30/2018 - 08:37).  Could this be a configuration option in `cfg.json`?

Thank you.

**Comment by AuspeXeu** [comment]
It could be, yes :) You're more than welcome to make a pull request for this. Unfortunately I am swamped with work and won't have time for this soon.

**Comment by xinthose** [comment]
OK.  I will try to give it a shot.  Thank you.

**Comment by AuspeXeu** [comment]
Closed due to inactivity
