### ISSUE TITLE
npm run build fails debian 8

### ISSUE THREAD

**Issue by nestlefox** [AuspeXeu/openvpn-status#195]
root@moon:~/openvpn-status# cat /root/.npm/_logs/2019-06-23T21_55_43_270Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.9.0
3 info using node@v11.15.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle openvpn-status@4.2.13~prebuild: openvpn-status@4.2.13
6 info lifecycle openvpn-status@4.2.13~build: openvpn-status@4.2.13
7 verbose lifecycle openvpn-status@4.2.13~build: unsafe-perm in lifecycle true
8 verbose lifecycle openvpn-status@4.2.13~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/openvpn-status/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle openvpn-status@4.2.13~build: CWD: /root/openvpn-status
10 silly lifecycle openvpn-status@4.2.13~build: Args: [ '-c', 'vue-cli-service build' ]
11 silly lifecycle openvpn-status@4.2.13~build: Returned: code: 137  signal: null
12 info lifecycle openvpn-status@4.2.13~build: Failed to exec build script
13 verbose stack Error: openvpn-status@4.2.13 build: `vue-cli-service build`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:193:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:193:13)
13 verbose stack     at maybeClose (internal/child_process.js:999:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
14 verbose pkgid openvpn-status@4.2.13
15 verbose cwd /root/openvpn-status
16 verbose Linux 4.9.0-8-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v11.15.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 137
22 error openvpn-status@4.2.13 build: `vue-cli-service build`
22 error Exit status 137
23 error Failed at the openvpn-status@4.2.13 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]

**Comment by AuspeXeu** [comment]
Which eslint version are you using in your `package.json`?
