### ISSUE TITLE
VPN IP format

### ISSUE THREAD

**Issue by shiioo** [AuspeXeu/openvpn-status#20]
Hey!

Not really an issue, more like a question.

I've upgraded to the very last revision and now the VPN IPs listed are converted into MAC addresses upon couple seconds after loading the interface.
Is this an intended behavior?

**Comment by AuspeXeu** [comment]
Definitely not ... which version do you have in the `package.json`?

**Comment by shiioo** [comment]
4.1.6

https://pastebin.com/E2m5iqj1

**Comment by AuspeXeu** [comment]
Hmm .... what does your `server.conf` look like?

**Comment by shiioo** [comment]
https://pastebin.com/LCp1Br5v

UDP & TAP as this network is mainly used for gaming (old games with only direct IP/LAN connectivity).

**Comment by AuspeXeu** [comment]
I have never used `dev tap` maybe you could provide the `openvpn-status.log`?

**Comment by shiioo** [comment]
I could but I've found the issue looking at it: the log also reports the MAC address instead of the VPN IP and that's most likely why
Apparently the only way to make it report an IP instead of a MAC is by changing TAP to TUN, which would prevent my network to work correctly (in my case).

There's probably no way around this I suppose. Though it's not really an issue for me.
