### ISSUE TITLE
Only one client shown

### ISSUE THREAD

**Issue by tmkis2** [AuspeXeu/openvpn-status#216]
openvpn status says 5 clients actually logged in but only one is shown in web interface.

OpenVPN 2.3.10 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jan  9 2019

Any idea?

**Comment by AuspeXeu** [comment]
What authentication do you use?

**Comment by tmkis2** [comment]
Client certificates

**Comment by AuspeXeu** [comment]
Hm. My setup uses the same method and works just fine. Can you provide the log of the application?
