### ISSUE TITLE
sluggish performance with 50 clients connected

### ISSUE THREAD

**Issue by robinleblon** [AuspeXeu/openvpn-status#22]
We currently have about 50 clients connected, and the web app has become rather sluggish on page load.
It take approximately 20 seconds before the web app becomes responsive, after which point it is very responsive and fast again.
Server has plenty of memory and cpu power and does not go higher than 5% load.

**Comment by xinthose** [comment]
What browser are you using?  Mine works quickly with about 30 clients, accessed from Google Chrome, and hosted from Windows 7.

**Comment by AuspeXeu** [comment]
Is it any better with the latest version?

**Comment by robinleblon** [comment]
We are currently testing the newest version, and will provide feedback asap.

**Comment by robinleblon** [comment]
It appears the issue still occurs with the latest version (4.1.14)
I have sent you on e-mail address with information where you can observe this problem in real life.

**Comment by AuspeXeu** [comment]
Seems like you have some issues with your websocket connection. Don't think this is an issue of openvpn-status.

![screen shot 2018-10-24 at 22 30 08](https://user-images.githubusercontent.com/2115696/47438150-79245000-d7dc-11e8-830c-f647c21751b9.png)

**Comment by AuspeXeu** [comment]
Pushed a new version, maybe that fixes it ;)

**Comment by stefaancm** [comment]
Performance is better with this new release, still somewhat sluggish but certainly usable.

**Comment by AuspeXeu** [comment]
Can I access the deployment with the same link you sent me?

**Comment by AuspeXeu** [comment]
Closed due to inactivity
