### ISSUE TITLE
It will only show the mac address for a TAP server

### ISSUE THREAD

**Issue by Edll** [AuspeXeu/openvpn-status#261]
Hello,

On an OpenVPN Tap server, the Virtual MAC address of the client is displayed in the client list instead of the Virtual IP address.

This is because the CLIENT_LIST with the Virtual Address field is read first in the data stream and then again in the ROUTING_TABLE. Here is listet the MAC address of the client is used instead of the Virtual Address. 

I have now added the following line. But I don't know how this affects a TUN server.

>  } else if (data.startsWith('ROUTING_TABLE') && this.state === STATE.status) {
      const props = data.split('\t').slice(1, data.length + 1)
      this.clients.forEach(vpnClient => {
        if (vpnClient['Real Address'] === props[this.clientProps.indexOf('Real Address')])
          this.clientProps.forEach((prop, idx) => {
               if(prop !== 'Virtual Address'){
                 vpnClient[prop] = prepProperty(props[idx])
               }
          })
      })
    }

**Comment by AuspeXeu** [comment]
I'll try that on my `TUN` sever and give you feedback :)
