### ISSUE TITLE
Connected clients aren't displayed

### ISSUE THREAD

**Issue by johndave9296** [AuspeXeu/openvpn-status#285]
As said in the title, I am using it's server as a VPN but when I tried to access it's server status, it's not showing any connected user/s. Already placed a "management 127.0.0.1 9296" line onto my server.conf of openvpn but it still doesn't show up. I hope you guys can help me.

![image](https://user-images.githubusercontent.com/8472952/64152500-5aaccd80-ce5f-11e9-96aa-adeed0c9f9cf.png)

**Comment by AuspeXeu** [comment]
Are the two programs running on the same machine? What's your `cfg.json` look like?

**Comment by jaydee9296** [comment]
It looks like this sir.

![image](https://user-images.githubusercontent.com/8472952/64183842-16402280-ce9d-11e9-955d-1a49f35b4f7d.png)

**Comment by AuspeXeu** [comment]
Are the two programs running on the same machine?

**Comment by jaydee9296** [comment]
Yes both NPM and NODEJS Sir.

**Comment by AuspeXeu** [comment]
I mean. What machine is the `openvpn` server running on and what server is the `openvpn-status` running on?

**Comment by jaydee9296** [comment]
it is running on Microsoft Azure HK Located Sir. However for how many minutes on running it, the terminal shows like these.

![image](https://user-images.githubusercontent.com/8472952/64264028-3b976400-cf63-11e9-8c42-1235a32e005f.png)

**Comment by AuspeXeu** [comment]
in the cfg.json set `host` to `127.0.0.1`

**Comment by jaydee9296** [comment]
Thanks it worked!

**Comment by jaydee9296** [comment]
I just need to re-up this... I am using two VPS. One is for the OpenVPN and the other one is for the OpenVPN status. It's not working anymore even though I am using a remote IP.

**Comment by AuspeXeu** [comment]
It's probably a firewall issue.

**Comment by jaydee9296** [comment]
How would that be possible to unblock it's firewall sir?

**Comment by AuspeXeu** [comment]
No idea, you have to ask your VPS provider.

**Comment by jaydee9296** [comment]
But why is it working the last time sir by which I thought this is working on multiple remote servers.

**Comment by jaydee9296** [comment]
Also sir, have I configured it properly that the line I used on server.conf on my VPN Server is

management 127.0.0.1 9296

While on the cfg.json is this

"servers": [{"name": "ASD","host": "server_ip","man_port": 9296}],

**Comment by AuspeXeu** [comment]
127.0.0.1 needs to be replaced with the server ip

**Comment by jaydee9296** [comment]
It's okay Sir since I am the only one using it. I hope this would be resolved sir.

**Comment by jaydee9296** [comment]
I've used the server IP but it's still not working.

**Comment by jaydee9296** [comment]
@aldrinimbag18 Tried it but the riskier part is di kaya ng virtual server ko ang nodejs and also MS Azure gamit ko din po. :)
