### ISSUE TITLE
Feature request: Support multiple OpenVPN instances

### ISSUE THREAD

**Issue by Waester** [AuspeXeu/openvpn-status#3]
If I have understood the config correctly. Openvpn-status only supports monitoring one instance of OpenVPN. Is it possible to add support to monitor multiple instances? For example I am running 2 instances of OpenVPN in port TCP 443 and UDP 1194.

**Comment by AuspeXeu** [comment]
That is exactly how it works. Sounds like a good idea to support multiple instances :) Any suggestions how the interface could support this?

**Comment by Waester** [comment]
Hmm. Seeing as how the current setup is that you pull information from openvpn-status file, you could do something like this in the config.json
```
{
  "port": 3013,
  "VPN01": {
    "logFile": "/etc/openvpn/openvpn-status_VPN01.log"
  },
  "VPN02": {
    "logFile": "/etc/openvpn/openvpn-status_VPN02.log"
  }
}
```

And in the webpage you could just add a server selection tab in the upper left corner which lets you select which server to view.

**Comment by AuspeXeu** [comment]
Any chance you would be willing to implement this @Waester ? :)
