### ISSUE TITLE
Manually running server on Windows 7 error

### ISSUE THREAD

**Issue by xinthose** [AuspeXeu/openvpn-status#32]
Version: 4.1.17
OS: Windows 7, 64-bit
Browser: Chrome 71

When I run the server manually and a new client connects, I see this error:
```
C:\Users\admin\Documents\openvpn-status-4.1.17>node server.js
(node:4628) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'C
lient ID' of undefined
    at clientToEntry (C:\Users\admin\Documents\openvpn-status-4.1.17\server.js:7
0:16)
    at client.on.cl (C:\Users\admin\Documents\openvpn-status-4.1.17\server.js:16
9:21)
    at emitOne (events.js:116:13)
    at client.emit (events.js:211:7)
    at getClients.then (C:\Users\admin\Documents\openvpn-status-4.1.17\openvpn.j
s:82:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:4628) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:4628) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

```
The new client does not show in the webpage.
Note: this is the first time using the new management port instead of the connect/disconnect scripts in version 4.0.25.

**Comment by AuspeXeu** [comment]
Can you insert `console.log(client)` before line 70 of the `server.js` file, run it again and provide the output?

**Comment by xinthose** [comment]
My OpenVPN server has multiple clients connected already.  I see only the first one on the webpage.  Any new connecting clients has the client as `undefined`.

First already connected client:
```
{ 'Common Name': 'GIL7162',
  'Real Address': 'XX.XX.XX.XX:XXX',
  'Virtual Address': 'XX.XX.XX.XX',
  'Bytes Received': 3978,
  'Bytes Sent': 7201,
  'Connected Since': 'Wed Jan 02 08:34:16 2019',
  'Connected Since (time_t)': 1546439656,
  Username: undefined,
  'Last Ref': 'Wed Jan 02 08:34:16 2019',
  'Last Ref (time_t)': 1546439656 }
```
New client connecting:
`undefined`

**Comment by AuspeXeu** [comment]
That's weird ... that's also the most difficult to debug. Can you do `console.log(data)` before line 19 in `openvpn.js` ?

**Comment by xinthose** [comment]
OK.  [Here ](https://pastebin.com/vG8ihrMY)it is.  Was the management console method ever tested on Windows?  I assume everything works fine on Linux.

**Comment by AuspeXeu** [comment]
Ah, shoot. Can you change it to `console.log(data.toString())` ?

**Comment by xinthose** [comment]
OK.  I think you're right.  When submitting my PR, I had to change the line breaks in VisualStudio Code to LF from CRLF ([StackOverflow post](https://stackoverflow.com/a/52418013/4056146)) before running `npm run build` on Windows.  If I didn't I would get a whole bunch of these errors: `Expected linebreaks to be 'LF' but found 'CRLF'`.

**Comment by xinthose** [comment]
> Ah, shoot. Can you change it to `console.log(data.toString())` ?
> I would guess that it has something to do with windows line break characters. Somewhere around the code that uses `'\r\n'`.

I emailed you the log.

**Comment by AuspeXeu** [comment]
Hm ... it seems fine tho. I just checked. It successfully split the data by line. I don't have a windows openvpn installation I can use for debugging ... maybe you can play around with it a bit and log certain stuff?

**Comment by xinthose** [comment]
OK.  So the problem is that `client` is `undefined` but `data` is not.  The problem is probably with string parsing then.  I would imagine the OpenVPN management port is OS agnostic.  Version 4.0.25 worked fine for me.  I will see what I can do.

**Comment by xinthose** [comment]
Everything works fine on Windows Server 2012 R2 from master branch 7ceaa1de40b93cb248b1b64e3a85b5842d36807b

**Comment by AuspeXeu** [comment]
So can this be considered resolved? :)

**Comment by xinthose** [comment]
Sure.  I have not tested the latest build on Windows 7.

**Comment by xinthose** [comment]
I can confirm that this issue still exists on Windows 7 (openvpn-status version 4.2.12).  Perhaps Windows 7 will just not be supported?
