### ISSUE TITLE
DeprecationWarning: A boolean value was passed to options.operatorsAliases. This is a no-op with v5 and should be removed

### ISSUE THREAD

**Issue by qizai123** [AuspeXeu/openvpn-status#354]
**I ran docker-compose and got the following feedback, and the service could not be accessed? I don't know what went wrong.**

[root@izuf6ds2yjlk65hcoeaylvz openvpn-status]# docker-compose --version
docker-compose version 1.24.1, build 4667896b
[root@izuf6ds2yjlk65hcoeaylvz openvpn-status]# docker --version
Docker version 19.03.4, build 9013bf583a

`[root@izuf6ds2yjlk65hcoeaylvz openvpn-status]# docker-compose -f docker-compose.yml up

Creating network "openvpn-status_default" with the default driver
Creating openvpn-status ... done
Attaching to openvpn-status
openvpn-status    | 
openvpn-status    | > openvpn-status@4.2.3 start /usr/src/app
openvpn-status    | > node server.js
openvpn-status    | 
openvpn-status    | (node:24) [SEQUELIZE0004] DeprecationWarning: A boolean value was passed to options.operatorsAliases. This is a no-op with v5 and should be removed.`

**Comment by AuspeXeu** [comment]
It's just a warning for now. Should not affect anything.

**Comment by qizai123** [comment]
Yes, I solved the problem. Bind binding 0.0.0.0 is required to be accessed. However, I still have a question. In the panel, only the assigned IP and source IP address can be displayed. Can I increase the vpn username that shows the login?

**Comment by AuspeXeu** [comment]
Not at this point. I am only using configurations that rely on certificates so I don't have that use case.
