### ISSUE TITLE
IP geo locate service maxmind is not publicly available anymore

### ISSUE THREAD

**Issue by DorianScholz** [AuspeXeu/openvpn-status#388]
The geo IP DB from maxmind is not available publicly anymore according to this blog post:
https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

So, starting the docker image of openvpn-status fails with this error:
Error: getaddrinfo ENOTFOUND geolite.maxmind.com geolite.maxmind.com:443

Since the docker image available on the docker registry is not quite up to date it does not include this fix to allow startup without the geo IP DB:
https://github.com/AuspeXeu/openvpn-status/commit/b01889fdbab7a1f46abb51e2d8f58e7a2c807a6e

**Comment by AuspeXeu** [comment]
Relinked to this repo so the docker image should be up to date again in a few minutes.

**Comment by xinthose** [comment]
On a fresh install, `node server.js` yields this error:
```
[Error: ENOENT: no such file or directory, open `./GeoLite2-City.mmdb`]
{
   errno: -2,
   code: 'ENOENT',
   syscall: 'open',
   path: './GeoLite2-City.mmdb'
}
```

**Comment by AuspeXeu** [comment]
Maybe this can be used to fix this issue https://github.com/maxmind/GeoIP2-node

**Comment by xinthose** [comment]
I suppose.  Perhaps Maxmind GeoLite `accountID` and `licenseKey` could be added to `cfg.json`.  I was just able to sign up for an account here: https://www.maxmind.com/en/geolite2/signup.  We can use their free databases if you really want to keep the map.

**Comment by AuspeXeu** [comment]
Were you able to use the package I posted previously?

**Comment by xinthose** [comment]
I'm sorry.  I have not tried.  All of my experience is in Angular, I have none in Vue.  Personally, I would like to create my own monitor in Angular.
