### ISSUE TITLE
Create a Windows 7 branch

### ISSUE THREAD

**Issue by xinthose** [AuspeXeu/openvpn-status#392]
Hello,

Thank you for fixing the MaxMind issue.  Can you please create a new branch named `v4.0.25-Windows7` so I can create a pull request?  I have that release working for Windows 7 right now.

**Comment by AuspeXeu** [comment]
You should not need me to create a branch in order to do this :)
https://www.dasblinkenlichten.com/how-to-create-a-github-pull-request-pr/

**Comment by xinthose** [comment]
I want to push to a branch on your repository.  I cannot do this until the branch exists.

**Comment by AuspeXeu** [comment]
You won't be able to do this anyways, since you don't have write access. You have a fork?

**Comment by xinthose** [comment]
Maybe it's best I just keep the code on my local fork.  Websockets is not working for some reason.  Yes, I do have a fork with a branch: https://github.com/xinthose/openvpn-status/tree/v4.0.25-Windows7
