### ISSUE TITLE
Nodejs version requirements

### ISSUE THREAD

**Issue by sabbath88** [AuspeXeu/openvpn-status#4]
Hello.
What is the minimum version requirement for this app?

**Comment by AuspeXeu** [comment]
Do you have any requirements on this why you can't use the latest version?

**Comment by sabbath88** [comment]
I had difficulty with raspberry pi (1st gen.) with raspbian.
Seems that my system was outdated.. node was somewhere around v0.10.29. After some web dig it was updated to v4.0.0, but that was still not enough. Still experienced syntax error on start.  After some more digging I found working solution:

> download the correct tarball from https://nodejs.org/dist/ For example:
> 
> cd ~
> wget https://nodejs.org/dist/latest/node-v7.10.0-linux-armv6l.tar.gz
> tar -xzf node-v7.10.0-linux-armv6l.tar.gz
> node-v7.10.0-linux-armv6l/bin/node -v
> 
> The last command should print v6.2.1.
> 
> Now you can copy it to /usr/local
> 
> cd node-v7.10.0-linux-armv6l/
> sudo cp -R * /usr/local/
> 
> For testing add /usr/local/bin to your path
> 
> export PATH=$PATH:/usr/local/bin
> node -v
> npm -v

Also executing command:
> npm install
installed some missing components.
After it all I got it working. But something need to be polished:
https://imagebin.ca/v/3M6dEqBwrDt8
My openvpn-status.log contains:
```
TITLE,OpenVPN 2.3.4 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jan 23 2016
TIME,Thu May 11 11:47:38 2017,1494496058
HEADER,CLIENT_LIST,Common Name,Real Address,Virtual Address,Bytes Received,Bytes Sent,Connected Since,Connected Since (time_t),Username
CLIENT_LIST,client-mi,[REAL_IP_REMOVED]:46589,10.8.0.18,35013,61566,Thu May 11 11:46:25 2017,1494495985,UNDEF
HEADER,ROUTING_TABLE,Virtual Address,Common Name,Real Address,Last Ref,Last Ref (time_t)
ROUTING_TABLE,10.8.0.18,client-mi,[REAL_IP_REMOVED]:46589,Thu May 11 11:46:48 2017,1494496008
GLOBAL_STATS,Max bcast/mcast queue length,0
END
```
Any ideas?

**Comment by AuspeXeu** [comment]
Hi, sorry. I am quite busy these days. Will have a look at it tomorrow.

**Comment by AuspeXeu** [comment]
Your log file looks different to mine. I am on version 2.4.1 have you set any options to change the default log file?

**Comment by AuspeXeu** [comment]
@sabbath88 I just published an updated version which should fix this :) please update and let me know whether it works.

**Comment by sabbath88** [comment]
Seems that your fix works well, at last at test server. I have to try it at production.

**Comment by AuspeXeu** [comment]
@sabbath88 Let me know how it goes

**Comment by sabbath88** [comment]
Works excellent.

**Comment by AuspeXeu** [comment]
@sabbath88 I just released a brand new version. Would be great if you could give it a try :)
