### ISSUE TITLE
could not connect to management console

### ISSUE THREAD

**Issue by yash-habilelabs** [AuspeXeu/openvpn-status#431]
Hi
i have an openvpn server running over 1194 port. when i tried to setup this project as per doc and trying to conenct with my server it's showing me the error while my server hasn't any password.
![image](https://user-images.githubusercontent.com/49152077/77303765-8028f800-6d19-11ea-8c66-21b229d0eaee.png)

**Comment by AuspeXeu** [comment]
You need to make sure the server is on the same machine and the management option is provided in the `server.conf`

**Comment by RAJANAGORI** [comment]
Hi
I added the management option in the server.conf file and restart the machine, but no reflection over the browser.
Thanks in advance

**Comment by shenglong209** [comment]
@RAJANAGORI  open that port in firewall first

**Comment by RAJANAGORI** [comment]
> @RAJANAGORI open that port in firewall first

i'm not using any firewall right now

**Comment by RAJANAGORI** [comment]
> @RAJANAGORI open that port in firewall first

Are you able to setup this?

**Comment by AuspeXeu** [comment]
Make sure you can ping the server machine from your status machine.

**Comment by yash-habilelabs** [comment]
> d to make sure the server is on the same machine and the management option

Hi 
we are at the same machine and write the option is provided in the  conf
but we aren't getting ping from the port i.e. 7656

**Comment by AuspeXeu** [comment]
Are you using docker?

**Comment by yash-habilelabs** [comment]
no

**Comment by AuspeXeu** [comment]
I cannot help you with this then, it's nothing wrong with this app you'll have to figure out your networking issues somehow.
