### ISSUE TITLE
Management console is sometimes connected and sometimes not. 

### ISSUE THREAD

**Issue by RAJANAGORI** [AuspeXeu/openvpn-status#436]
When I start Pm2.json and check the logs 
![image](https://user-images.githubusercontent.com/32300516/77618412-4693ff00-6f5c-11ea-9669-aa3fd3affd56.png)
it shows this and nothing reflect on the browser 
![image](https://user-images.githubusercontent.com/32300516/77618491-6c210880-6f5c-11ea-9969-bed3dafeb133.png)

![image](https://user-images.githubusercontent.com/32300516/77623483-2e28e200-6f66-11ea-9a14-818e4a9bdd42.png)

**Comment by AuspeXeu** [comment]
You'll have to check the connection between your status server machine and the openvpn machine.

**Comment by RAJANAGORI** [comment]
> You'll have to check the connection between your status server machine and the openvpn machine.

both are on the same machine

**Comment by AuspeXeu** [comment]
what does your configuration look like?

**Comment by RAJANAGORI** [comment]
![image](https://user-images.githubusercontent.com/32300516/77648213-c5edf680-6f8d-11ea-82ae-ef2c998f3a2e.png)

what are the content in servers folders ? my server configuration ?
