### ISSUE TITLE
im having a hard time installing this  on debian 9

### ISSUE THREAD

**Issue by freetextmike** [AuspeXeu/openvpn-status#454]
Everything seems to work fine until this

> Get:263 http://deb.debian.org/debian buster/main amd64 libdata-dump-perl all 1.23-1 [29.5 kB]
Get:264 http://deb.debian.org/debian buster/main amd64 libpadwalker-perl amd64 2.3-1+b1 [20.1 kB]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.1.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@4.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-15T14_56_42_063Z-debug.log

i tried then installing sqlite3 manually and buidling it 

>npm run build
> openvpn-status@4.2.32 build /home/mik334mikee/openvpn-status
> vue-cli-service build
⠙  Building for production...
 WARNING  Compiled with 3 warnings                                                                    3:02:15 PM
 warning  
asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  css/chunk-vendors.c12a84ce.css (512 KiB)
  js/chunk-vendors.b5a8d75b.js (1.1 MiB)
 warning  
entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). 
This can impact web performance.
Entrypoints:
  app (1.62 MiB)
      css/chunk-vendors.c12a84ce.css
      js/chunk-vendors.b5a8d75b.js
      css/app.746e770b.css
      js/app.0ec68ad0.js
 warning  
webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your appli
cation.
For more info visit https://webpack.js.org/guides/code-splitting/
  File                                   Size              Gzipped
  dist/js/chunk-vendors.b5a8d75b.js      1129.16 KiB       268.06 KiB
  dist/js/app.0ec68ad0.js                21.05 KiB         7.26 KiB
  dist/css/chunk-vendors.c12a84ce.css    511.73 KiB        58.64 KiB
  dist/css/app.746e770b.css              1.02 KiB          0.25 KiB
  Images and other types of assets omitted.
 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html

and nothing on my IP:3013

please can you point me to the right direction i tried scrolling the resolved issues but i cant seeem to find any useful information, or tell me what machine do you recommend to run this. Thanks!

EDIT: tried starting it manually

>openvpn-status# node server.js
/home/mik334mikee/openvpn-status/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:88
        throw new Error(`Please install ${moduleName} package manually`);
        ^
Error: Please install sqlite3 package manually
    at ConnectionManager._loadDialectModule (/home/mik334mikee/openvpn-status/node_modules/sequelize/lib/dialect
s/abstract/connection-manager.js:88:15)
    at new ConnectionManager (/home/mik334mikee/openvpn-status/node_modules/sequelize/lib/dialects/sqlite/connec
tion-manager.js:22:21)
    at new SqliteDialect (/home/mik334mikee/openvpn-status/node_modules/sequelize/lib/dialects/sqlite/index.js:1
4:30)
    at new Sequelize (/home/mik334mikee/openvpn-status/node_modules/sequelize/lib/sequelize.js:324:20)
    at Object.<anonymous> (/home/mik334mikee/openvpn-status/database.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/mik334mikee/openvpn-status/server.js:11:12)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

but i arleady install sqlite3 how come it returns error

**Comment by AuspeXeu** [comment]
It seems like the module is not installed correctly. Try wiping your `node_modules` folder and `package-lock.json` / `yarn.lock` and reinstall everything.

**Comment by freetextmike** [comment]
created a new instances and really has a problem on npm install sqlite3
>npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.1.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@4.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-15T16_51_04_913Z-debug.log

any recommendations?

**Comment by AuspeXeu** [comment]
Since this is an sqlite3 related issue, I'd ask here https://github.com/mapbox/node-sqlite3
