### ISSUE TITLE
So i manage now to install sqlite3

### ISSUE THREAD

**Issue by freetextmike** [AuspeXeu/openvpn-status#455]
Good Day
Sorry for being a bother,
I manage to install sqlite3 on my machine with --unsafe-per param
>(node:790) UnhandledPromiseRejectionWarning: SequelizeConnectionError: SQLITE_CANTOPEN: unabl
e to open database file
    at Database.<anonymous> (/home/mik334mikee/openvpn-status/node_modules/sequelize/lib/dial
ects/sqlite/connection-manager.js:61:34)
(node:790) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originat
ed either by throwing inside of an async function without a catch block, or by rejecting a pr
omise which was not handled with .catch(). To terminate the node process on unhandled promise
 rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.
html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:790) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the 
future, promise rejections that are not handled will terminate the Node.js process with a non
-zero exit code.

this was returned when run server.js

**Comment by freetextmike** [comment]
managed run your work Thanks!

npm install sqlite3 --unsafe-per did the trick

debian9stretch

**Comment by xinthose** [comment]
I just posted an answer on what worked for me.  I had `sqllite3` installation problems on Ubuntu 20.04 LTS and Node.js 14: https://stackoverflow.com/a/65890943/4056146

**Comment by xinthose** [comment]
I cannot get `sqlite3` installed on Windows Server 2012 R2, therefore I cannot get this repository to work.  It works great on Linux though.
