### ISSUE TITLE
Sqlite file data.sqlite

### ISSUE THREAD

**Issue by rajesh8614** [AuspeXeu/openvpn-status#461]
Hi
1. There is no data in Clents table sqlite database. May be in database.js file entry is not correct `const Client = sequelize.define('Clent', {`
2. In sqlite database it creates table by name `Clents` It adds "s" character at the end

```
const Client = sequelize.define('Clent', {
  id: mkId(),
  server: {type: Sequelize.INTEGER},
  name: {type: Sequelize.STRING},
  sent: {type: Sequelize.INTEGER, defaultValue: 0},
  received: {type: Sequelize.INTEGER, defaultValue: 0}
})

module.exports = {
  init: () => Promise.all([Log.sync(), Client.sync()]),
  Log,
  Client,
  op: Sequelize.Op
}
```

**Comment by AuspeXeu** [comment]
The database has not been touched in ages so I doubt there is a bug there, it's more likely that the data does not reach the database.
