### ISSUE TITLE
Is this allowing to recode urls?

### ISSUE THREAD

**Issue by jeffreyouni** [AuspeXeu/openvpn-status#497]
Hi, I am wondering to know if this allows recoding URLs?

**Comment by AuspeXeu** [comment]
Can you elaborate what you mean by that?

**Comment by jeffreyouni** [comment]
> Can you elaborate what you mean by that?

Hello, I meant, can I use "OpenVPN-status" to sniff URLs that pass by OpenVPN.
Thanks!

**Comment by AuspeXeu** [comment]
No
