### ISSUE TITLE
GeoIp local database

### ISSUE THREAD

**Issue by denser** [AuspeXeu/openvpn-status#499]
How can i use my Geoip mmdb from /usr/share/GeoIP?

**Comment by AuspeXeu** [comment]
The path to the database is specified [here](https://github.com/AuspeXeu/openvpn-status/blob/master/utils.js#L28)

**Comment by denser** [comment]
With docker no need to use this method. I found way to add volume...
```volumes:
      - ./servers:/usr/src/app/servers
      - /usr/share/GeoIP/GeoLite2-City.mmdb:/usr/src/app/GeoLite2-City.mmdb
