### ISSUE TITLE
Management console wont connect

### ISSUE THREAD

**Issue by denser** [AuspeXeu/openvpn-status#500]
While testing, compose up and see this:
`Could not connect to management console @ 127.0.0.1:7656, retrying in 10s`
Meanwhile netstat says:
`tcp        0      0 127.0.0.1:7656          0.0.0.0:*               LISTEN      0          116158182  2858418/openvpn`
Server json file:
`{"name": "Server","host": "127.0.0.1","man_port": 7656}`

Any help?

**Comment by denser** [comment]
Ok, solved in "crap" way. Service listens localhost inside container and we cant listen ports on host from container. So i lookup "ip a" for docker bridge ip and bind openvpn management to it ant point that IP in servers.json

May be we have more elegant way?

UPDATE: add some example
ip a
```
64: br-aa667404c257: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:0e:47:b6:e4 brd ff:ff:ff:ff:ff:ff
    inet 192.168.66.1/25 brd 192.168.66.127 scope global br-aa667404c257
       valid_lft forever preferred_lft forever
    inet6 fe80::42:eff:fe47:b6e4/64 scope link
       valid_lft forever preferred_lft forever
```
server.json
```
{"name": "Server","host": "192.168.66.1","man_port": 7656}
```
server.conf (ovpn)
```
management 192.168.66.1 7656
```

**Comment by AuspeXeu** [comment]
You could run the container in the host network. Otherwise, no.

**Comment by denser** [comment]
We can use 0.0.0.0 on listen management, so docker bridge automatically can accept connections, but still need to change ip in server.json.

Btw nice tool you made.

**Comment by denser** [comment]
I presume its not issue... its more looks like improvement)) Closed.
