### ISSUE TITLE
Access Webpage on other computers

### ISSUE THREAD

**Issue by xinthose** [AuspeXeu/openvpn-status#52]
Hello.  How can I access the webpage elsewhere on the network?  I tried setting host to `0.0.0.0`.  I get `ERR_CONNECTION_REFUSED` in the browser.

**Comment by AuspeXeu** [comment]
This should work, yes.

**Comment by xinthose** [comment]
OK.  Strange.  I can hit the apache page on 192.168.2.150, but 192.168.2.150:3013 does not work.  I am running an Ubuntu VM in Windows.  I will check the Windows firewall rules.

**Comment by xinthose** [comment]
I see my issue.  I set `"host": "0.0.0.0"` and left out `bind`.  Thank you for your help.
