### ISSUE TITLE
Peer dependencies / Empty interface

### ISSUE THREAD

**Issue by shiioo** [AuspeXeu/openvpn-status#7]
I've spent several hours (literally) trying to update my old working v1.0.14 to the new v2.0.7 of this script to no luck so far, on a headless and up to date Raspbian system (Raspberry 3).

I've got the interface to work, but no sign of log usage. Shouldn't be a permission issue this time as I didn't touch the conf of OpenVPN (and it works with the v1 of your script).

I got those 2 warnings at the end of the install procedure though (out of 6, but the 4 other ones shouldn't be of concern):
> npm WARN eslint-config-standard@10.2.1 requires a peer of eslint-plugin-import@>=2.2.0 but none was installed.
> npm WARN eslint-config-standard@10.2.1 requires a peer of eslint-plugin-node@>=4.2.2 but none was installed.

I don't know if these are part of the issue. Not to mention I spent (lost dare I say) a huge amount of time figuring out how to -g(lobally) install those dependencies (which required others and wouldn't want to play nice - I really hate NodeJS) so I find them quite irritating, even if they're meaningless.

The logs generated by your script are empty. There's no sign of issue on those generated by pm2.
Nothing worthwile on the system logs.
At that point, I don't know what to do.

**Comment by AuspeXeu** [comment]
Can you post the contents of your openvpn log file.

**Comment by shiioo** [comment]
Here it is:

> OpenVPN CLIENT LIST
Updated,Sat Sep 16 20:29:21 2017
Common Name,Real Address,Bytes Received,Bytes Sent,Connected Since
marmottin,192.168.1.64:62886,1388689,16400661,Sat Sep 16 19:21:19 2017
ROUTING TABLE
Virtual Address,Common Name,Real Address,Last Ref
00:ff:10:b1:f7:3d,username,192.168.1.64:62886,Sat Sep 16 20:29:09 2017
GLOBAL STATS
Max bcast/mcast queue length,1
END

**Comment by AuspeXeu** [comment]
The problem is, that your virtual address seems to be a MAC address !?

**Comment by shiioo** [comment]
Yes, the main use of this VPN network is to connect friends that don't live in the same city in order to play old favourite games that only support LAN connectivity.
In that case, a TAP interface performs better, thus the MAC instead of the IP in the log :)

**Comment by AuspeXeu** [comment]
Well, in that case you changed something in your config because this was not intended to work in the previous version either. I update the source and push it in 5 min. Let me know whether it works with the new version.

**Comment by shiioo** [comment]
Thanks for the very prompt fix, though while it's starting, I can't access the interface anymore.

> You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: Cannot read property 'country' of null
    at entries.forEach (/home/pi/openvpn-status/server.js:46:32)
    at Array.forEach (<anonymous>)
    at updateServer (/home/pi/openvpn-status/server.js:44:11)
    at servers.forEach (/home/pi/openvpn-status/server.js:144:9)
    at Array.forEach (<anonymous>)
    at loadIPdatabase.then (/home/pi/openvpn-status/server.js:138:15)
    at <anonymous>
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: Cannot read property 'country' of null
    at entries.forEach (/home/pi/openvpn-status/server.js:46:32)
    at Array.forEach (<anonymous>)
    at updateServer (/home/pi/openvpn-status/server.js:44:11)
    at servers.forEach (/home/pi/openvpn-status/server.js:144:9)
    at Array.forEach (<anonymous>)
    at loadIPdatabase.then (/home/pi/openvpn-status/server.js:138:15)
    at <anonymous>

**Comment by AuspeXeu** [comment]
Can you try the following server.js and report the output to me?

https://pastebin.com/raw/sxNpMBpn

**Comment by shiioo** [comment]
Of course.

out-0.log:
> { vpn: '00:ff:10:b1:f7:3d',
  name: 'username',
  pub: '192.168.1.64',
  timestamp: 1505661081 }

**Comment by AuspeXeu** [comment]
Just pushed a patch. Can you get the latest version and run `npm run build` again and let me know how it goes.

**Comment by shiioo** [comment]
All good now!

Thanks you very much, and sorry for the trouble :)

**Comment by shiioo** [comment]
I'm reviving this old issue as after upgrading to the last revision of your script (4.0.18), I'm back again with an empty interface, which may be caused by the same thing (MAC instead of IP).

**Comment by AuspeXeu** [comment]
However, you use the `status.sh` now, no?

**Comment by shiioo** [comment]
Yeah, though I found my issue and was about to delete this as it was clearly me messing up (I forgot to copy the server config into its proper location upon editing it...).

It's working fine (thanks for keeping this up to date!) and sorry for the bother =)

**Comment by AuspeXeu** [comment]
@shiioo no worries, what was the issue if I may ask.

**Comment by shiioo** [comment]
I did the correct changes, but I forgot to copy the updated server.conf from my draft folder to its proper location (yeah, I'm ashamed, the easiest part...).

**Comment by AuspeXeu** [comment]
Hah, ok I see. Keep me updated in case you find things to improve 👍
