### ISSUE TITLE
management password

### ISSUE THREAD

**Issue by rkearsley** [AuspeXeu/openvpn-status#82]
Hi!

Does openvpn-status support management authentication to the openvpn server (pw-file) ?
From the man page: 

>  --management IP port [pw-file]
>               Enable  a TCP server on IP:port to handle daemon management functions.  pw-file, if specified, is a password file (password on first line) or "stdin" to
>               prompt from standard input.  The password provided will set the password which TCP clients will need to provide in order to access management functions.

Thanks
Richard

**Comment by AuspeXeu** [comment]
Not yet, more than happy to review a PR if you want to give it a shot :)
