### ISSUE TITLE
VPN stop working after edit server.conf

### ISSUE THREAD

**Issue by PrzemekSkw** [AuspeXeu/openvpn-status#87]
Hi, I'm new to servers. I install debian 9 on VPS and then install openvpn on it. I try to install openvpn-monitor but failed. Now I try to install Your openvpn-status but when I edit server.conf and add at the end of file line: `management...` I cannot connect from my laptop to vpn.
Regards,
Przemek

**Comment by AuspeXeu** [comment]
Check the error log of openvpn first. I guess there must be a typo in the configuration file.

**Comment by PrzemekSkw** [comment]
@AuspeXeu Hi, thanks for response. Could You tell me what to seek in logs because there's millions of lines and I'm not familiar with that.

**Comment by AuspeXeu** [comment]
I would search for errors and warnings first

**Comment by PrzemekSkw** [comment]
@AuspeXeu Is it the right command to search the logs?
`grep VPN /var/log/syslog`

**Comment by AuspeXeu** [comment]
Since this is not really a problem of openvpn-status. Could you ask this question in an OpenVPN forum?

**Comment by PrzemekSkw** [comment]
@AuspeXeu When I add today those lines: `management...` to server.conf my VPN works. But I cannot open app in browser in http://127.0.0.1:3013. 
I try to run manually but also don't work.
![Zrzut ekranu z 2019-03-22 12-00-24](https://user-images.githubusercontent.com/25219988/54818768-4f435c80-4c9a-11e9-82ee-e2cfc39b8e1d.png)

**Comment by PrzemekSkw** [comment]
@AuspeXeu Hi, noone want to help me on openvpn forum so maybe You will tell me how to remove openvpn-status?

**Comment by AuspeXeu** [comment]
Just remove the management entry from the conf

**Comment by PrzemekSkw** [comment]
@AuspeXeu OK, thank You for Your help.
