### ISSUE TITLE
Regex doesn't work for current openvpn (on Arch)

### ISSUE THREAD

**Issue by philipflohr** [AuspeXeu/openvpn-status#9]
The regex does not work with the current default log format for openvpn 2.4 on ArchLinux

The following regex and the following lines are working as expected

  `const rawEntries = content.map((line) => line.match(/CLIENT_LIST,([a-zA-Z]+),([0-9]+.[0-9]+.[0-9]+.[0-9]+):[0-9]+,([0-9]+.[0-9]+.[0-9]+.[0-9]+),.*,.*,.*,(.*),.*,.*,.*,.*/)).filter((itm) => itm)

const entries = rawEntries.map((entry) => ({
    vpn: entry[3],
    name: entry[1],
    pub: entry[2],
    timestamp: moment(new Date(entry[4])).unix()
  })).filter((entry) => entry.name !== 'UNDEF')`

**Comment by AuspeXeu** [comment]
Can you file a PR for this? :)

**Comment by AuspeXeu** [comment]
@philipflohr I just released a new version that does not need a log file any more. Let me know when you have some time to check it out :)
